language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
  - echo "$DOCKER_USERNAME"

script:
  - docker --version # print the version for logging
  - docker build -t ci-travis-ex1 .
  - docker tag ci-travis-ex1 awais16/ci-travis-ex1:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push awais16/ci-travis-ex1